### ISSUE TITLE
Questions::OFtutorial08_customBC: In what situation, we need to prescribe such a velocity profile at INLET?

### ISSUE THREAD

**Issue by randomwangran** [UnnamedMoose/BasicOpenFOAMProgrammingTutorials#15]
In typical pipe flow, the velocity profile will become the pattern
similar to the red line in the following plot.

Usually, people apply a fixed value velocity at inlet. Then start the
steady-state simulation (e.g., simpleFoam). The velocity profile will
look like the red line.

So, in what kind of situation, we need to prescribe such a velocity
profile (blue line)?

![difference](https://user-images.githubusercontent.com/8197831/87723309-9f93d700-c787-11ea-96a5-e853bed72ccb.png)

**Comment by UnnamedMoose** [comment]
Hi, the most common situation for this would be shortening the length of pipe needed in order to achieve a fully-developed flow. But it'd be much better to use a turbulent profile for that rather than what the tutorial actually uses. For RANS it might not matter that much, but this is very often done fo LES, for instance (usually with recycling of turbulence as well). See here for instance (paragraph right above RESULTS): http://users.monash.edu.au/~bburn/pdf/csiro99_pipe.pdf

**Comment by randomwangran** [comment]
[Thanks for sharing, I will read the paper and explore the turbulence.](https://github.com/randomwangran/what-s-being-on-my-mind/commit/905c3ffcec9d487945765bc7339017bb5508a4fa)
